run_pars_list <- list(
	# UNINFORMATIVE PRIORS: ---------------------------------------------------
	# 1) B117 against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 2) B117 against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 3) B1429 against everyone else
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, B1429Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 4) B1429 against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B1429Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# PRIORS INFORMED BY PREVIOUS ANALYSIS: -----------------------------------
	# 5) B117 against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 6) B117 against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 7) B1429 against everyone else
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, B1429Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 8) B1429 against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B1429Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# LOW PRIORS: -------------------------------------------------------------
	# 9) B117 against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 10) B117 against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 11) B1429 against everyone else
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, B1429Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 12) B1429 against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B1429Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# AGE ANALYSIS, UNINFORMATIVE PRIORS: -------------------------------------
	# 13) >=40 against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, AgeGroup%in%c("40-49","50-59","60+"))$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# SYMPTOMS ANALYSIS, UNINFORMATIVE PRIORS: --------------------------------
	# 14) Symptomatic against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, Symptoms==1)$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		)
	)
