run_pars_list <- list(
	# UNINFORMATIVE PRIORS: ---------------------------------------------------
	# 1) Alpha against everyone else: 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 2) Alpha against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 3) Epsilon against everyone else
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 4) Epsilon against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 5) Delta against everyone else
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 6) Delta against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# PRIORS INFORMED BY PREVIOUS ANALYSIS: -----------------------------------
	# 7) Alpha against everyone else: 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 8) Alpha against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 9) Epsilon against everyone else
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 10) Epsilon against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 11) Delta against everyone else
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 12) Delta against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# LOW PRIORS: -------------------------------------------------------------
	# 13) Alpha against everyone else: 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# 14) Alpha against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=filter(ct_dat_refined, B117Status=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 15) Epsilon against everyone else
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 16) Epsilon against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=c(filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 17) Delta against everyone else
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 18) Delta against everyone else, excluding other known variants 
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# AGE ANALYSIS, UNINFORMATIVE PRIORS: -------------------------------------
	# 19) >=40 against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, AgeGroup %in% c("40-49","50-59","60+"))$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),	
	# SYMPTOMS ANALYSIS, UNINFORMATIVE PRIORS: --------------------------------
	# 20) Symptomatic against everyone else: 
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, Symptoms==1)$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# DELTA BREAKTHROUGH ANALYSIS, UNINFORMATIVE PRIORS: -----------------------
	# 21) Look at delta breakthroughs:
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B16172Status=="Yes" & VaccineBreakthrough=="No")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes" & VaccineBreakthrough=="No")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes" & VaccineBreakthrough=="No")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes" & VaccineBreakthrough=="No")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes" & VaccineBreakthrough=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 22) Look at delta non-breakthroughs:
	list(excluded_rows=c(filter(ct_dat_refined, Lineage=="None")$RowID,
			filter(ct_dat_refined, B117Status=="Yes")$RowID,
			filter(ct_dat_refined, B1351Status=="Yes")$RowID,
			filter(ct_dat_refined, B16172Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, P1Status=="Yes")$RowID,
			filter(ct_dat_refined, B1427Status=="Yes")$RowID,
			filter(ct_dat_refined, B1429Status=="Yes")$RowID,
			filter(ct_dat_refined, B1525Status=="Yes")$RowID,
			filter(ct_dat_refined, B1526Status=="Yes")$RowID,
			filter(ct_dat_refined, B15261Status=="Yes")$RowID,
			filter(ct_dat_refined, B15262Status=="Yes")$RowID,
			filter(ct_dat_refined, B16171Status=="Yes")$RowID,
			filter(ct_dat_refined, B16173Status=="Yes")$RowID,
			filter(ct_dat_refined, P2Status=="Yes")$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes" & VaccineBreakthrough=="No")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes" & VaccineBreakthrough=="No")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes" & VaccineBreakthrough=="No")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes" & VaccineBreakthrough=="No")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 23) Compare delta breakthroughs against delta non-breakthroughs, uninformative:
	list(excluded_rows=c(filter(ct_dat_refined, !(B16172Status=="Yes" | AY1Status=="Yes" | AY2Status=="Yes" | AY3Status=="Yes"))$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes" & VaccineBreakthrough=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 24) Compare all breakthroughs to all non-breakthroughs:
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, VaccineBreakthrough=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 25) Compare Pfizer vs. J&J, uninformative priors: 
	list(excluded_rows=c(filter(ct_dat_refined, !(VaccineManufacturer%in%c("Pfizer-BioNTech","Johnson & Johnson / Janssen")))$RowID,
		filter(ct_dat_refined, (VaccineBreakthrough=="No"))$RowID),
		special_rows=filter(ct_dat_refined, VaccineManufacturer=="Johnson & Johnson / Janssen")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=14/2,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=30/2,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 26) Compare Pfizer vs. J&J, informed priors: 
	list(excluded_rows=c(filter(ct_dat_refined, !(VaccineManufacturer%in%c("Pfizer-BioNTech","Johnson & Johnson / Janssen")))$RowID,
		filter(ct_dat_refined, (VaccineBreakthrough=="No"))$RowID),
		special_rows=filter(ct_dat_refined, VaccineManufacturer=="Johnson & Johnson / Janssen")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 27) Compare Pfizer vs. J&J, low priors: 
	list(excluded_rows=c(filter(ct_dat_refined, !(VaccineManufacturer%in%c("Pfizer-BioNTech","Johnson & Johnson / Janssen")))$RowID,
		filter(ct_dat_refined, (VaccineBreakthrough=="No"))$RowID),
		special_rows=filter(ct_dat_refined, VaccineManufacturer=="Johnson & Johnson / Janssen")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 28) Compare breakthroughs to all non-breakthroughs, informative priors:
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, VaccineBreakthrough=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 29) Compare breakthroughs to all non-breakthroughs, low priors:
	list(excluded_rows=c(),
		special_rows=filter(ct_dat_refined, VaccineBreakthrough=="Yes")$RowID,
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 30) Compare delta breakthroughs against delta non-breakthroughs, informative:
	list(excluded_rows=c(filter(ct_dat_refined, !(B16172Status=="Yes" | AY1Status=="Yes" | AY2Status=="Yes" | AY3Status=="Yes"))$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes" & VaccineBreakthrough=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=2.7,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=7.4,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		),
	# 31) Compare delta breakthroughs against delta non-breakthroughs, low:
	list(excluded_rows=c(filter(ct_dat_refined, !(B16172Status=="Yes" | AY1Status=="Yes" | AY2Status=="Yes" | AY3Status=="Yes"))$RowID),
		special_rows=c(filter(ct_dat_refined, B16172Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY1Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY2Status=="Yes" & VaccineBreakthrough=="Yes")$RowID,
			filter(ct_dat_refined, AY3Status=="Yes" & VaccineBreakthrough=="Yes")$RowID),
		tpsd=2,
		dpmin=0,
		dpmean_prior=global_pars[["lod"]]/2,
		dpsd_prior=global_pars[["lod"]]/6,
		wpmin=0.25,
		wpmax=14,
		wpmean_prior=0,
		wpsd_prior=14/6,
		wrmin=2,
		wrmax=30,
		wrmean_prior=0,
		wrsd_prior=30/6,
		sigma_max=10,
		sigma_prior_scale=5,
		lambda=0.01,
		fpmean=1/log(10),
		trapfit=FALSE
		)
	)
	


# If you want to include all B117 and 11 non-B117: 
# excluded_rows = setdiff(ct_dat_refined %>% 
# 			filter(!(PersonID %in% (ct_dat_refined %>% 
# 				filter(B117Status != "Yes") %>% 
# 				group_by(PersonID) %>% 
# 				summarise() %>%
# 				pull(PersonID) %>% 
# 				sample(11)))) %>% 
# 			pull(RowID),filter(ct_dat_refined, B117Status=="Yes")$RowID)
